const [disease, setDisease] = useState([
  { name: "Malaria", key: "1" },
  { name: " Typhoid", key: "2" },
  { name: " Cholerah", key: "3" },
  { name: "HIV/AIDs", key: "4" },
  { name: " UTI", key: "5" },
  { name: " Pregnancy", key: "6" },
  { name: "Food poisoning", key: "7" },
  { name: "Covid 19", key: "8" },
  { name: "Arthritis", key: "9" },
  { name: "Skin cancer", key: "10" },
  { name: " Inadequate sleep", key: "11" },
  { name: "Starvation", key: "12" },
  { name: "Marasmus", key: "13" },
  { name: "Pneumonia", key: "14" },
  { name: "Common cold", key: "15" },
  { name: "Colon cancer", key: "16" },
  { name: "Cervical cance", key: "17" },
  { name: "Anaemia", key: "18" },
  { name: "Leukemia", key: "19" },
  { name: "Myopia/ Short-sightedness", key: "20" },
  { name: "Vitiligo", key: "21" },
  { name: "Long-sightedness", key: "22" },
  { name: "Headache", key: "1" },
  { name: "Jaundice", key: "2" },
  { name: "Prostrate cancer", key: "3" },
  { name: "Kwashiorkor", key: "4" },
  { name: "Breast cancer", key: "5" },
  { name: "Throat cancer", key: "6" },
  { name: "Dandruff", key: "7" },
  { name: "Constipation", key: "8" },
  { name: "Pain when urinating", key: "9" },
  { name: "Dirrhoea", key: "10" },
  { name: "Dry eyes", key: "11" },
  { name: "Fever", key: "12" },
  { name: "Body ache", key: "13" },
  { name: "Back sache", key: "14" },
  { name: "Dry cough", key: "15" },
  { name: "Loss of taste", key: "16" },
  { name: "Loss of smell", key: "17" },
  { name: "Dizziness", key: "18" },
  { name: "Insomnia", key: "19" },
  { name: "Nausea", key: "20" },
  { name: "Hair Loss", key: "21" },
  { name: "Pale eyes", key: "22" },
]);
